### ISSUE TITLE
Erorr or am i dumb ?

### ISSUE THREAD

**Issue by opferkind** [SamyR0/DDoS-Script#1]
nr one cmd tell me to use command samy.pl ? it doesnt exsist 

and if i dos/ddos  with cqHack.pl with enemies ip my inet shut down 🗡

**Comment by samuelctn** [comment]
use the command perl cqHack.pl that's the file name lol =))

ur using cmd ffs...

**Comment by opferkind** [comment]
what schould i use sry im noob ...

is it putty?
